# This file's format is documented at
# https://forge.rust-lang.org/triagebot/pr-assignment.html#configuration

# ------------------------------------------------------------------------------
# Labels
# ------------------------------------------------------------------------------

[autolabel."pr-not-reviewed"]
new_pr = true

# ------------------------------------------------------------------------------
# PR assignments
# ------------------------------------------------------------------------------

[assign]
